Simplify the JSON response
asfaltboy/explainshell pull request #2
Opened 2018-05-28 21:29 UTC by chrismwendt

This simplifies the JSON response so it's no longer tied to the structure that the HTML templates expect.

@asfaltboy @idank Once this is merged in (to `asfaltboy/explainshell`), https://github.com/idank/explainshell/pull/125 should automatically update and be ready to merge 👌

2018-05-30 18:53 UTC, asfaltboy requested changes
Overall looks really nice to me! Added a bunch of small comments below, thanks for the PR !

2018-05-30 18:53 UTC, asfaltboy commented on explainshell/web/views.py
> +    return [val for (_, val) in merged.items()]
can just `return merged.values()`

2018-05-30 18:53 UTC, asfaltboy commented on explainshell/web/views.py
> +    for item in l1+l2:
can use `itertools.chain` to avoid copying the lists into a 3rd lists

2018-05-30 18:53 UTC, asfaltboy commented on explainshell/web/views.py
> +    return [val for (_, val) in merged.items()]
can just `return merged.values()`

2018-05-30 18:53 UTC, asfaltboy commented on explainshell/web/views.py
> +        helpItemsDicts = [{ 'helpHTML': helpItem[0], 'helpclass': helpItem[1] } for helpItem in result['helptext']]
can be written like so for clarity:
```
        helpItemsDicts = [{
            'helpHTML': help_content, 'helpclass': help_class
        } for help_content, help_class in result['helptext']]
```

2018-05-30 18:53 UTC, asfaltboy commented on explainshell/web/views.py
> +        return render_template('explain.html', **result)
I actually prefer the previously used mapping `STATUS_TYPE_TEMPLATES` to a long list of if clause

2018-05-30 21:11 UTC, chrismwendt commented
Thanks for the tips! I updated this PR.

2018-05-31 07:10 UTC, asfaltboy approved these changes

2018-05-31 07:10 UTC, merged